kind: Service
apiVersion: v1
metadata:
  name: apis
  namespace: external
spec:
  type: ClusterIP
  selector:
    app: apis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apis
  name: apis
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: external
    spec:
      automountServiceAccountToken: false
      containers:
        - image: local/external/apis
          imagePullPolicy: IfNotPresent
          name: apis
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 256m
              memory: 128Mi
            requests:
              cpu: 128m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9091
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: external
      terminationGracePeriodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apis
  namespace: external
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: apis
