version: '2'
services:
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=bego
      - POSTGRES_DB=bego
      - POSTGRES_PASSWORD=password