apiVersion: v1
kind: ServiceAccount
metadata:
  name: external
  namespace: external
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-apis
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "namespaces", "endpoints"]
    verbs: ["get", "post", "put", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: external
  name: external-apis
subjects:
  - kind: ServiceAccount
    name: external-apis
    namespace: external
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: external-apis
  apiGroup: ""